//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlProyecto.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBControlProyectoEntities3 : DbContext
    {
        public DBControlProyectoEntities3()
            : base("name=DBControlProyectoEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblActividad> tblActividad { get; set; }
        public virtual DbSet<tblArea> tblArea { get; set; }
        public virtual DbSet<tblCargo> tblCargo { get; set; }
        public virtual DbSet<tblFirmaDigital> tblFirmaDigital { get; set; }
        public virtual DbSet<tblProfesion> tblProfesion { get; set; }
        public virtual DbSet<tblProfesional> tblProfesional { get; set; }
        public virtual DbSet<tblProfesionalxReunion> tblProfesionalxReunion { get; set; }
        public virtual DbSet<tblProyecto> tblProyecto { get; set; }
        public virtual DbSet<tblRecurso> tblRecurso { get; set; }
        public virtual DbSet<tblRecursoxActividad> tblRecursoxActividad { get; set; }
        public virtual DbSet<tblReunion> tblReunion { get; set; }
        public virtual DbSet<tblUsuario> tblUsuario { get; set; }
    }
}
