//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlProyecto.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblActividad()
        {
            this.tblRecursoxActividad = new HashSet<tblRecursoxActividad>();
        }
    
        public int id_actividad { get; set; }
        public string titulo { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_proyecto { get; set; }
        public Nullable<int> DNI { get; set; }
    
        public virtual tblProyecto tblProyecto { get; set; }
        public virtual tblProfesional tblProfesional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRecursoxActividad> tblRecursoxActividad { get; set; }
    }
}
