//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlProyecto.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProfesional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProfesional()
        {
            this.tblActividad = new HashSet<tblActividad>();
            this.tblProyecto = new HashSet<tblProyecto>();
        }
    
        public int DNI { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_firma { get; set; }
        public Nullable<int> id_area { get; set; }
        public Nullable<int> id_profesion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActividad> tblActividad { get; set; }
        public virtual tblArea tblArea { get; set; }
        public virtual tblFirmaDigital tblFirmaDigital { get; set; }
        public virtual tblProfesion tblProfesion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProyecto> tblProyecto { get; set; }
        public virtual tblProfesionalxReunion tblProfesionalxReunion { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
