//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlProyecto.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProyecto()
        {
            this.tblActividad = new HashSet<tblActividad>();
            this.tblReunion = new HashSet<tblReunion>();
        }
    
        public int id_proyecto { get; set; }
        public string tituloPro { get; set; }
        public System.DateTime fechaIniPro { get; set; }
        public System.DateTime fechaFinPro { get; set; }
        public string ubicacion { get; set; }
        public string distrito { get; set; }
        public string departamento { get; set; }
        public Nullable<int> DNI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActividad> tblActividad { get; set; }
        public virtual tblProfesional tblProfesional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReunion> tblReunion { get; set; }
    }
}
