//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlProyecto.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReunion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblReunion()
        {
            this.tblProfesionalxReunion = new HashSet<tblProfesionalxReunion>();
        }
    
        public int id_reunion { get; set; }
        public string tipoReunion { get; set; }
        public Nullable<int> id_proyecto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProfesionalxReunion> tblProfesionalxReunion { get; set; }
        public virtual tblProyecto tblProyecto { get; set; }
    }
}
